name: terraform

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  terraform-check:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Check Terraform Formatting
      run: |
        cd test-infra
        ls -l
        which terraform
        terraform fmt --check
    - name: Validate Terraform Templates
      run: |
        cd test-infra
        terraform validate
